#put parenthesis for the print function
#since old python did not use the parenthesis for it

import re, os

#list all files that end with .py
files = list(filter(lambda x: x.endswith('.py'), os.listdir()))
#replaces the original file, else creates a copy
#Go with false if you want a backup
inPlace = True

modified = '';
if not inPlace:
    modified = ' - modified.py'

for i in files:
    if i == 'Editor.py':#do not edit this file
        continue
    f = open(i, 'r')
    s = f.read()
    f.close()
    lst = re.findall('print\s*?[\'|\"].*?[\'|\"]', s)

    #if it is python 3.* or no print functions
    if lst == []:
        continue
    for j in lst:
        replace = 'print' + '(' + str(lst[0][5:])+ ')'
        s = s.replace(j, replace)
    f = open(i + modified, 'w')
    f.write(s)
    f.close()
